const getServico = () => {
    return [
        {
            id: 1,
            nome: 'Limpeza de Pele',
            descricao: 'Tratamento para remoção de impurezas da pele.',
            preco: 80.0,
            avaliacao: 4.5,
        },
        {
            id: 2,
            nome: 'Hidratação Facial',
            descricao: 'Tratamento para hidratar a pele e combater o ressecamento.',
            preco: 120.0,
            avaliacao: 5.0,
        },
        {
            id: 3,
            nome: 'Peeling Químico',
            descricao: 'Procedimento para renovar a pele, tratando manchas e rugas.',
            preco: 150.0,
            avaliacao: 3.5,
        },
        {
            id: 4,
            nome: 'Massagem Relaxante',
            descricao: 'Massagem para relaxar os músculos e aliviar o estresse.',
            preco: 90.0,
            avaliacao: 4.0,
        },
        {
            id: 5,
            nome: 'Corte de Cabelo',
            descricao: 'Corte de cabelo moderno e personalizado.',
            preco: 50.0,
            avaliacao: 4.8,
        },
        {
            id: 6,
            nome: 'Coloração de Cabelo',
            descricao: 'Coloração para mudar a cor dos cabelos de forma vibrante.',
            preco: 70.0,
            avaliacao: 4.2,
        },
        {
            id: 7,
            nome: 'Manicure e Pedicure',
            descricao: 'Cuidado das unhas, mãos e pés para uma aparência elegante.',
            preco: 40.0,
            avaliacao: 4.7,
        },
        {
            id: 8,
            nome: 'Depilação',
            descricao: 'Remoção de pelos indesejados para uma pele suave.',
            preco: 60.0,
            avaliacao: 4.1,
        },
        {
            id: 9,
            nome: 'Maquiagem Profissional',
            descricao: 'Maquiagem artística para eventos especiais.',
            preco: 100.0,
            avaliacao: 4.9,
        },
        {
            id: 10,
            nome: 'Tratamento Capilar',
            descricao: 'Tratamento intensivo para fortalecimento e brilho dos cabelos.',
            preco: 110.0,
            avaliacao: 4.6,
        },
        {
            id: 11,
            nome: 'Design de Sobrancelhas',
            descricao: 'Modelagem e design para realçar a expressão facial.',
            preco: 45.0,
            avaliacao: 4.4,
        },
        {
            id: 12,
            nome: 'Banho de Lua',
            descricao: 'Técnica que clareia os pelos do corpo de forma suave.',
            preco: 55.0,
            avaliacao: 4.3,
        },
        {
            id: 13,
            nome: 'Penteado Especial',
            descricao: 'Penteado elaborado para ocasiões especiais.',
            preco: 75.0,
            avaliacao: 4.7,
        },
        {
            id: 14,
            nome: 'Podologia',
            descricao: 'Cuidado especializado para os pés, unhas e calosidades.',
            preco: 65.0,
            avaliacao: 4.0,
        },
        {
            id: 15,
            nome: 'Tratamento Anti-idade',
            descricao: 'Procedimento para redução de sinais de envelhecimento da pele.',
            preco: 130.0,
            avaliacao: 4.9,
        },
        {
            id: 16,
            nome: 'Bronzeamento Artificial',
            descricao: 'Método para obter um bronzeado dourado sem exposição solar.',
            preco: 85.0,
            avaliacao: 4.2,
        },
        {
            id: 17,
            nome: 'Drenagem Linfática',
            descricao: 'Massagem que estimula o sistema linfático para redução de inchaços.',
            preco: 95.0,
            avaliacao: 4.6,
        },
        {
            id: 18,
            nome: 'Tratamento para Acne',
            descricao: 'Protocolo para combater e prevenir a acne facial.',
            preco: 75.0,
            avaliacao: 4.4,
        },
        {
            id: 19,
            nome: 'Alongamento de Cílios',
            descricao: 'Técnica para cílios mais longos e volumosos.',
            preco: 55.0,
            avaliacao: 4.8,
        },
        {
            id: 20,
            nome: 'Escova Progressiva',
            descricao: 'Alisamento capilar para redução de volume e frizz.',
            preco: 120.0,
            avaliacao: 4.5,
        },
        // Adicione mais tratamentos conforme necessário
    ];
};

export default getServico;
